# Site settings
title: "Hoang Anh Nguyen - AI Researcher"
description: "AI Researcher specializing in AI for Software Development, Large Language Models, and Continual Learning"
author: "Hoang Anh Nguyen"
email: "anh.nh204511@gmail.com"
url: "https://anhnh2002.github.io"
baseurl: ""

# Social links
github_username: anhnh2002
linkedin_username: anh-nguyen-hoang-20860a252
google_scholar: FjCF32MAAAAJ

# SEO settings
lang: en_US
twitter:
  username: # Add if you have Twitter
  card: summary_large_image

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  publications:
    output: false
  projects:
    output: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - outline-portfolio.md

# Include files
include:
  - _pages

# Default values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Hoang Anh Nguyen"